### ISSUE TITLE
Broken links in overview

### ISSUE THREAD

**Issue by jerlich** [wehr-lab/autopilot#123]
In the graphic at the bottom of https://docs.auto-pi-lot.com/en/latest/guide/overview.html the links point to e.g. https://docs.auto-pi-lot.com/en/latest/guide/autopilot.hardware.cameras.html but they should point to https://docs.auto-pi-lot.com/en/latest/hardware/cameras.html

I was going to make the changes myself and make a PR, but i am not familiar with `rst` and how the docs structure gets converted into the web page.

I think the changes need to happen here (https://github.com/wehr-lab/autopilot/blob/ced9dca4715f32324650fe4a0e0ecab8fd8965d8/docs/includes/module_map.html) but not sure about it.

**Comment by sneakers-the-rat** [comment]
Love this issue.

Yes, i changed the directory structure which was formerly flat into being nested directories as it got pretty unwieldy. Thought i had searched for all the times those kinds of urls were used but missed those! forgot that I had made that page autogenerate with javascript, must have been having a d3 spree at the time.

love this attention to detail & willingness to submit small issues, very helpful, keep em coming <3 

fixed in 
https://github.com/wehr-lab/autopilot/commit/587ecde128eeb28d0bbe9be1bf41087910ef55a6
https://github.com/wehr-lab/autopilot/commit/69249d551a6a8b63bdcc6614176cdaf3d7a5af75
https://github.com/wehr-lab/autopilot/commit/c61a13df13098da109b20c61e5c238291a4da6ca
https://github.com/wehr-lab/autopilot/commit/ebf2619c2c6f0c8a0a0274719635fac77f87c106

and merged back to main!
