### ISSUE TITLE
gap all step error

### ISSUE THREAD

**Issue by lucasogit** [wehr-lab/autopilot#132]
The gap all step of the gap_laserPV protocol it not working (no sound and no input response) and gave this error:

> Traceback (most recent call last):
>   File "/home/lab/git/autopilot/autopilot/core/subject.py", line 733, in prepare_run
>     grad_obj = autopilot.get('graduation', grad_type)
>   File "/home/lab/git/autopilot/autopilot/utils/registry.py", line 149, in get
>     raise ValueError(ex_text)
> ValueError: Could not find subclass of <class 'autopilot.tasks.graduation.Graduation
>

**Comment by sneakers-the-rat** [comment]
This was due to a version mismatch, where protocols created before v0.4.* used the accursed `TASK_LIST` and `GRADUATION_LIST` which mapped strings to classes, and the keys would not necessarily match the name of the classes, eg. `{'accuracy': Accuracy, 'n_trials', NTrials}` -- changing the strings in the protocol .json file solves this!
